### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by shnopy** [glowingrunes/glowingrunes.github.io#1]
Hi, I was wondering how to do animations. I've got the same bird as you and wondered if there was a way to know what you needed to put to make the animations work

**Comment by shnopy** [comment]
I think I worked it out :)

**Comment by glowingrunes** [comment]
Hi @shnopy . Sorry, I was absorbed in Final Fantasy 14! Yeah, you need to add the **animation-mixer** attribute to your entity tag. When viewing the model on Sketchfab you can see if it has multiple animation clips. If it does you can specify which clip(s) you want to play. Look [here](https://github.com/donmccurdy/aframe-extras/tree/master/src/loaders#animation) for a list of other things you can do with the **animation-mixer** component.
